[package]
name = "rustc_codegen_tpde"
version.workspace = true
edition.workspace = true

[dependencies]
cxx = "^1.0.197"

[build-dependencies]
cxx-build = "^1.0.197"
cmake = "0.1.58"

[lib]
crate-type = ["rlib"]

[dev-dependencies]
libtest-mimic = "0.7"
pretty_assertions = "1.4"
similar = "3.1.1"

[[test]]
name = "runner"
harness = false
